/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-07 17:03:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1565196935224L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <!-- Required meta tags -->\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("        <link rel=\"icon\" href=\"img/favicon.png\" type=\"image/png\">\n");
      out.write("        <title>하나은행</title>\n");
      out.write("        <!-- Bootstrap CSS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/linericon/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/lightbox/simpleLightbox.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/nice-select/css/nice-select.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/animate-css/animate.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"vendors/swiper/css/swiper.min.css\">\n");
      out.write("        <!-- main css -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/my-slider.css\"/>\n");
      out.write("\t\t<script src=\"js/ism-2.2.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <!--================Header Menu Area =================-->\n");
      out.write("        <header class=\"header_area\">\n");
      out.write("            <div class=\"main_menu\">\n");
      out.write("            \t<nav class=\"navbar navbar-expand-lg navbar-light\">\n");
      out.write("\t\t\t\t\t<div class=\"container box_1620\">\n");
      out.write("\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t\t\t\t<a class=\"navbar-brand logo_h\" href=\"index.html\"><img src=\"img/hana_logo.PNG\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav menu_nav justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.html\">Home</a></li> \n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"about-us.html\">About</a></li> \n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"service.html\">Services</a>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"portfolio.html\">Portfolio</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"portfolio-details.html\">Portfolio Details</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"elements.html\">Elements</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</li> \n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Blog</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"single-blog.html\">Blog Details</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</li> \n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.jsp\">로그인</a>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\"><i class=\"fa fa-behance\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"search\"><i class=\"lnr lnr-magnifier\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("            \t</nav>\n");
      out.write("            </div>\n");
      out.write("        </header>");
      out.write("\n");
      out.write("        <!--================Header Menu Area =================-->\n");
      out.write("        \n");
      out.write("        <!--================Home Banner Area =================-->\n");
      out.write("        <section class=\"banner_area\">\n");
      out.write("            <div class=\"banner_inner d-flex align-items-center slide_area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class='container'>\n");
      out.write("\t\t\t\t\t\t<div class=\"ism-slider\" data-transition_type=\"fade\" data-play_type=\"loop\" id=\"my-slider\">\n");
      out.write("\t\t\t\t\t\t  <ol>\n");
      out.write("\t\t\t\t\t\t    <li>\n");
      out.write("\t\t\t\t\t\t      <img src=\"ism/image/slides/flower-729514_1280.jpg\">\n");
      out.write("\t\t\t\t\t\t    </li>\n");
      out.write("\t\t\t\t\t\t    <li>\n");
      out.write("\t\t\t\t\t\t      <img src=\"ism/image/slides/beautiful-701678_1280.jpg\">\n");
      out.write("\t\t\t\t\t\t    </li>\n");
      out.write("\t\t\t\t\t\t    <li>\n");
      out.write("\t\t\t\t\t\t      <img src=\"ism/image/slides/summer-192179_1280.jpg\">\n");
      out.write("\t\t\t\t\t\t    </li>\n");
      out.write("\t\t\t\t\t\t  </ol>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!--================End Home Banner Area =================-->\n");
      out.write("        \n");
      out.write("        <!--================Project Area =================-->\n");
      out.write("        <section class=\"project_area\">\n");
      out.write("        \t<div class=\"row m0\">\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/news1.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/project-2.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/project-3.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/project-4.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/project-5.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"col-lg-4 col-md-6 p0\">\n");
      out.write("        \t\t\t<div class=\"project_item\">\n");
      out.write("        \t\t\t\t<img src=\"img/project/project-6.jpg\" alt=\"\">\n");
      out.write("        \t\t\t\t<div class=\"hover_text\">\n");
      out.write("        \t\t\t\t\t<h4>Exotic <br />Mangrove</h4>\n");
      out.write("        \t\t\t\t\t<div class=\"cat\">\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">Lifestyle</a>\n");
      out.write("        \t\t\t\t\t\t<a href=\"#\">People</a>\n");
      out.write("        \t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t<a class=\"main_btn\" href=\"#\">View More</a>\n");
      out.write("        \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>\n");
      out.write("        </section>\n");
      out.write("        <!--================End Project Area =================-->\n");
      out.write("        \n");
      out.write("        <!--================ start footer Area  =================-->\t\n");
      out.write("        <footer class=\"footer-area\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-3  col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h6 class=\"footer_title\">About Biznance</h6>\n");
      out.write("                            <p>The world has become so fast paced that people donât want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point where images and videos are</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-3 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h6 class=\"footer_title\">Navigation Links</h6>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-4\">\n");
      out.write("                                    <ul class=\"list\">\n");
      out.write("                                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                                        <li><a href=\"#\">Feature</a></li>\n");
      out.write("                                        <li><a href=\"#\">Services</a></li>\n");
      out.write("                                        <li><a href=\"#\">Portfolio</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-4\">\n");
      out.write("                                    <ul class=\"list\">\n");
      out.write("                                        <li><a href=\"#\">Team</a></li>\n");
      out.write("                                        <li><a href=\"#\">Pricing</a></li>\n");
      out.write("                                        <li><a href=\"#\">Blog</a></li>\n");
      out.write("                                        <li><a href=\"#\">Contact</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("                            </div>\t\t\t\t\t\t\t\n");
      out.write("                        </div>\n");
      out.write("                    </div>\t\t\t\t\t\t\t\n");
      out.write("                    <div class=\"col-lg-3 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h6 class=\"footer_title\">Newsletter</h6>\n");
      out.write("                            <p>For business professionals caught between high OEM price and mediocre print and graphic output, </p>\t\t\n");
      out.write("                            <div id=\"mc_embed_signup\">\n");
      out.write("                                <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\" method=\"get\" class=\"subscribe_form relative\">\n");
      out.write("                                    <div class=\"input-group d-flex flex-row\">\n");
      out.write("                                        <input name=\"EMAIL\" placeholder=\"Email Address\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Email Address '\" required=\"\" type=\"email\">\n");
      out.write("                                        <button class=\"btn sub-btn\"><span class=\"lnr lnr-location\"></span></button>\t\t\n");
      out.write("                                    </div>\t\t\t\t\t\t\t\t\t\n");
      out.write("                                    <div class=\"mt-10 info\"></div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-3 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget instafeed\">\n");
      out.write("                            <h6 class=\"footer_title\">InstaFeed</h6>\n");
      out.write("                            <ul class=\"list instafeed d-flex flex-wrap\">\n");
      out.write("                                <li><img src=\"img/instagram/Image-01.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-02.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-03.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-04.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-05.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-06.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-07.jpg\" alt=\"\"></li>\n");
      out.write("                                <li><img src=\"img/instagram/Image-08.jpg\" alt=\"\"></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\t\t\t\t\t\t\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div class=\"border_line\"></div>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row footer-bottom d-flex justify-content-between align-items-center\">\n");
      out.write("                    <p class=\"col-lg-8 col-md-8 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\n");
      out.write("                    <div class=\"col-lg-4 col-md-4 footer-social\">\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("        </footer>\n");
      out.write("\t\t<!--================ End footer Area  =================-->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- Optional JavaScript -->\n");
      out.write("        <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n");
      out.write("        <script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("        <script src=\"js/popper.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/stellar.js\"></script>\n");
      out.write("        <script src=\"vendors/lightbox/simpleLightbox.min.js\"></script>\n");
      out.write("        <script src=\"vendors/nice-select/js/jquery.nice-select.min.js\"></script>\n");
      out.write("        <script src=\"vendors/isotope/imagesloaded.pkgd.min.js\"></script>\n");
      out.write("        <script src=\"vendors/isotope/isotope-min.js\"></script>\n");
      out.write("        <script src=\"vendors/owl-carousel/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("        <script src=\"vendors/counter-up/jquery.waypoints.min.js\"></script>\n");
      out.write("        <script src=\"vendors/counter-up/jquery.counterup.js\"></script>\n");
      out.write("        <script src=\"js/mail-script.js\"></script>\n");
      out.write("        <script src=\"vendors/popup/jquery.magnific-popup.min.js\"></script>\n");
      out.write("        <script src=\"vendors/swiper/js/swiper.min.js\"></script>\n");
      out.write("        <script src=\"js/theme.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
